name: CI file
on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: checout code
        uses: actions/checkout@v4

      - name: Build docker images
        run: docker build -t company-website .    